# Generated by Django 4.1.4 on 2023-02-07 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mynotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 7, 18, 11, 2, 143743))),
                ('title', models.CharField(max_length=100)),
                ('cate', models.CharField(max_length=100)),
                ('myfiles', models.FileField(upload_to='Notes')),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 7, 18, 11, 2, 143743)),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='password',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='username',
            field=models.EmailField(max_length=254),
        ),
    ]
