# Generated by Django 4.1.4 on 2023-02-09 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mynotes_usersignup_created_alter_usersignup_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(blank=True, default=datetime.datetime(2023, 2, 9, 14, 49, 18, 621086))),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.BigIntegerField(max_length=10)),
                ('Messages', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='mynotes',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 9, 14, 49, 18, 621086)),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 9, 14, 49, 18, 621086)),
        ),
    ]
